// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI0TsNQ6oLaJGtojPtmoNM2SbbdQsawO0',
    appId: '1:129875558924:web:df694575635b67ec92a429',
    messagingSenderId: '129875558924',
    projectId: 'customer-app-2024',
    authDomain: 'customer-app-2024.firebaseapp.com',
    storageBucket: 'customer-app-2024.appspot.com',
    measurementId: 'G-NQ55G5FSCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdkNQZfGLm5hWn0b2Pp9SlhxRl2NqUn6k',
    appId: '1:129875558924:android:882dad1a5364d58e92a429',
    messagingSenderId: '129875558924',
    projectId: 'customer-app-2024',
    storageBucket: 'customer-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHBJBqD6y_Q-GmRKSniSo0WDgo2FryY4A',
    appId: '1:129875558924:ios:d667e68bdaca824592a429',
    messagingSenderId: '129875558924',
    projectId: 'customer-app-2024',
    storageBucket: 'customer-app-2024.appspot.com',
    iosBundleId: 'com.example.customerApp',
  );
}
